# Generated by Django 5.0.6 on 2024-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.TextField(max_length=100)),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
    ]
